# Generated by Django 3.2.4 on 2021-06-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='carsimage')),
                ('speed', models.DecimalField(blank=True, decimal_places=0, max_digits=6)),
            ],
        ),
    ]
