# Generated by Django 3.2.4 on 2021-06-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20210622_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='in_color',
            new_name='interior_color',
        ),
    ]
