# Generated by Django 3.2.4 on 2021-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='carsimage'),
        ),
    ]
